import { chapterIndex } from "./chapter-index.js";

const $ = (s) => document.querySelector(s);
const app = $("#app");
const state = JSON.parse(localStorage.getItem("xavier-js-book") || '{"read":[],"xp":0,"sound":true,"reduced":false,"badges":[]}');
const sounds = Object.fromEntries(["click","hover","success","error","page-turn","badge"].map(n=>[n,new Audio(`assets/sounds/${n}.wav`)]));
Object.values(sounds).forEach(a=>a.volume=.35);
function save(){localStorage.setItem("xavier-js-book",JSON.stringify(state)); updateStats();}
function play(n){if(!state.sound)return; const a=sounds[n]; a.currentTime=0;a.play().catch(()=>{});}
function updateStats(){$("#xpStat").textContent=`⚡ ${state.xp} XP`;$("#readStat").textContent=`${state.read.length} / 53`;}
function route(r){location.hash=r;}
function menu(open){$("#sidebar").classList.toggle("open",open);$("#overlay").classList.toggle("show",open);}
$("#openMenu").onclick=()=>{play("click");menu(true)};$("#closeMenu").onclick=()=>menu(false);$("#overlay").onclick=()=>menu(false);
document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>{play("click");menu(false);route(b.dataset.route)});
document.querySelectorAll("button").forEach(b=>b.addEventListener("mouseenter",()=>play("hover")));
$("#printBook").onclick=()=>{menu(false);route("print");setTimeout(()=>window.print(),400);};

function home(){
 app.innerHTML=`<section class="hero"><div><div class="eyebrow">53-chapter interactive course</div><h1>JavaScript Mastery <span>by Xavier</span></h1><p>Read JavaScript as a real book, explore original diagrams, study editor-style code examples, then practice when you feel ready.</p><div class="buttons"><button class="btn-primary" id="readStart">Start Reading</button><button class="btn-secondary" id="bookOnly">Open Book Mode</button></div></div><div class="code-window"><div class="code-head"><span class="dots">● ● ●</span> starter.js</div><pre>const learner = "Xavier";
const goal = "Master JavaScript";

function levelUp() {
  return "Let's build! 🚀";
}

console.log(levelUp());</pre></div></section>
<section class="grid"><div class="card"><div class="metric">${state.read.length} / 53<small>Chapters read</small></div></div><div class="card"><div class="metric">⚡ ${state.xp}<small>Total XP</small></div></div><div class="card"><div class="metric">📚 ${chapterIndex.length}<small>Book chapters</small></div></div><div class="card"><div class="metric">✪ ${state.badges.length}<small>Badges unlocked</small></div></div></section>
<section class="section-title"><div class="eyebrow">Book first</div><h2>Read without interruptions</h2><p>Book Mode shows the cover, introduction, table of contents, chapters, diagrams, and final author page — nothing else.</p></section>
<section class="chapter-grid">${chapterIndex.slice(0,6).map(c=>`<article class="chapter-card" data-ch="${c.id}"><b>CHAPTER ${c.id}</b><h3>${c.title}</h3><p>${c.subtitle}</p></article>`).join("")}</section>`;
 $("#readStart").onclick=()=>openChapter(state.read.at(-1)||1,"learn"); $("#bookOnly").onclick=()=>route("book"); bindCards();
}
function bindCards(){document.querySelectorAll("[data-ch]").forEach(el=>el.onclick=()=>{play("click");openChapter(+el.dataset.ch,"learn")})}
function book(){
 app.innerHTML=`<div class="book-shell"><section class="book-cover"><img src="assets/icons/javascript.svg" alt="JavaScript logo"><div class="eyebrow">A complete reading edition</div><h1>JavaScript Mastery<br><span>by Xavier</span></h1><p>A 53-chapter journey from your first line of JavaScript to carefully planned browser projects. Read in order, jump from the index, or print a light-theme edition when you are ready.</p><div class="buttons"><button class="btn-primary" id="tocStart">Read Introduction</button><button class="btn-secondary" id="printFromBook">Print Book</button></div></section><section class="chapter" style="margin-top:24px"><div class="chapter-meta">Index of the book</div><h1>Table of Contents</h1><div class="toc">${chapterIndex.map(c=>`<button data-ch="${c.id}">${String(c.id).padStart(2,"0")}. ${c.title}</button>`).join("")}<button data-author>About the Author — Xavier</button></div></section></div>`;
 $("#tocStart").onclick=()=>openChapter(1,"book");$("#printFromBook").onclick=()=>{$("#printBook").click()};bindCards();document.querySelector("[data-author]").onclick=()=>route("author");
}
async function getChapter(id){return (await import(`./chapters/${chapterIndex[id-1].file}`)).default;}
async function openChapter(id,mode="book"){
 const c=await getChapter(id); if(!state.read.includes(id)){state.read.push(id);state.xp+=15;save();play("page-turn");}
 const content=c.sections.map((s,i)=>`<section><h2>${i+1}. ${s.heading}</h2>${s.paragraphs.map(p=>`<p>${p}</p>`).join("")}${s.code?`<div class="codeblock"><div class="code-head"><span class="dots">● ● ●</span> example.js</div><pre>${escapeHtml(s.code)}</pre></div>`:""}${i===1?`<img class="diagram" src="${c.diagram}" alt="Diagram for ${c.title}">`:""}</section>`).join("");
 const practice=mode==="learn"?`<section class="activity"><div class="eyebrow">Practice</div><h2>${c.task.prompt}</h2><textarea class="editor" id="taskCode">${c.task.starter}</textarea><div class="buttons"><button class="btn-primary" id="checkTask">Check Code</button><button class="btn-secondary" id="runTask">Run Code</button></div><div class="console" id="taskResult">Write code, then run or check it here.</div></section><section class="activity"><div class="eyebrow">Quick Check</div><h2>${c.quiz.question}</h2>${c.quiz.options.map((o,n)=>`<button class="btn-secondary quiz" data-a="${n}">${String.fromCharCode(65+n)}. ${o}</button>`).join("<br>")}<div class="console" id="quizResult">Choose the best answer.</div></section>`:"";
 app.innerHTML=`<article class="chapter"><div class="chapter-meta">Chapter ${c.id} · ${c.module} · ${c.readTime}</div><h1>${c.title}</h1><p class="lead">${c.subtitle}</p>${content}<aside class="note"><strong>Chapter recap</strong><br>${c.summary.join("<br>")}</aside>${practice}<div class="chapter-actions"><button class="btn-secondary" id="backBook">← Table of Contents</button><button class="btn-primary" id="nextChapter">${id===53?"Finish the Book →":"Continue Reading →"}</button></div></article>`;
 $("#backBook").onclick=()=>route(mode==="learn"?"learn":"book");$("#nextChapter").onclick=()=>id===53?route("author"):openChapter(id+1,mode);
 if(mode==="learn"){ $("#runTask").onclick=()=>runCode($("#taskCode").value,$("#taskResult"));$("#checkTask").onclick=()=>checkTask(c);document.querySelectorAll(".quiz").forEach(b=>b.onclick=()=>checkQuiz(c,+b.dataset.a));}
}
function escapeHtml(s){return s.replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]));}
function runCode(code,out){const logs=[];try{new Function("console",{log:(...x)=>logs.push(x.join(" "))})( {log:(...x)=>logs.push(x.join(" "))});new Function("console",code)({log:(...x)=>logs.push(x.join(" "))});out.textContent=logs.join("\n")||"Code ran without console output.";play("success");}catch(e){out.textContent="Error: "+e.message;play("error")}}
function checkTask(c){const code=$("#taskCode").value, out=$("#taskResult");if(code.includes("console.log")||/function|=>/.test(code)){state.xp+=c.task.xp;save();out.textContent=`Correct structure detected! +${c.task.xp} XP`;play("success");}else{out.textContent="Add a function, arrow function, or console.log result, then try again.";play("error")}}
function checkQuiz(c,a){const out=$("#quizResult");if(a===c.quiz.answer){state.xp+=20;save();out.textContent="Correct! +20 XP";play("success");}else{out.textContent="Try once more. Return to the chapter text for the clue.";play("error")}}
function learn(){app.innerHTML=`<section class="section-title"><div class="eyebrow">Learn & Practice</div><h2>Choose a chapter</h2><p>Reading includes practice and quick checks at the end of every chapter.</p></section><section class="chapter-grid">${chapterIndex.map(c=>`<article class="chapter-card" data-ch="${c.id}"><b>CHAPTER ${c.id} · ${c.module}</b><h3>${c.title}</h3><p>${c.subtitle}</p></article>`).join("")}</section>`;bindCards()}
function codelab(){app.innerHTML=`<section class="section-title"><div class="eyebrow">Code Lab</div><h2>Run JavaScript in your browser</h2><p>Test examples, explore an idea, and use the console output to understand what your code does.</p></section><section class="activity"><textarea id="labCode" class="editor">const greeting = "Hello from Code Lab";\nconsole.log(greeting);</textarea><div class="buttons"><button class="btn-primary" id="runLab">Run Code</button><button class="btn-secondary" id="clearLab">Clear</button></div><div id="labOut" class="console">Console ready.</div></section>`;$("#runLab").onclick=()=>runCode($("#labCode").value,$("#labOut"));$("#clearLab").onclick=()=>{$("#labCode").value="";$("#labOut").textContent="Console cleared."}}
function progress(){app.innerHTML=`<section class="section-title"><div class="eyebrow">Your reading journey</div><h2>${state.read.length} of 53 chapters read</h2><p>${state.xp} XP collected. Continue reading anytime; your progress is saved on this device.</p></section><div class="card"><div class="metric">${Math.round(state.read.length/53*100)}%<small>Book completion</small></div></div><section class="chapter-grid" style="margin-top:18px">${chapterIndex.map(c=>`<article class="chapter-card" data-ch="${c.id}"><b>${state.read.includes(c.id)?"READ ✓":"NOT READ"}</b><h3>${c.id}. ${c.title}</h3></article>`).join("")}</section>`;bindCards()}
function badges(){const earned=[];if(state.read.length>=1)earned.push("First Page");if(state.read.length>=10)earned.push("Ten Chapters");if(state.read.length>=26)earned.push("Halfway Reader");if(state.read.length===53)earned.push("JavaScript Master");state.badges=earned;save();app.innerHTML=`<section class="section-title"><div class="eyebrow">Badges</div><h2>Milestones worth keeping</h2><p>Badges unlock from your reading journey and practice.</p></section><section class="chapter-grid">${["First Page","Ten Chapters","Halfway Reader","JavaScript Master"].map(b=>`<article class="card"><div class="metric">${earned.includes(b)?"✪":"○"}</div><h3>${b}</h3><p>${earned.includes(b)?"Unlocked":"Keep reading to unlock"}</p></article>`).join("")}</section>`}
function author(){app.innerHTML=`<section class="author"><img src="assets/icons/javascript.svg" alt=""><div class="eyebrow">End of the book</div><h1>JavaScript Mastery<br><span style="color:var(--yellow)">by Xavier</span></h1><p>Created by <strong>Mr Xavier</strong> as an original interactive JavaScript learning book. This edition brings together 53 chapters, readable source files, diagrams, code examples, a Code Lab, and a printable book layout.</p><p><strong>GitHub:</strong> <a href="https://github.com/mrxavier53" target="_blank" rel="noreferrer">github.com/mrxavier53</a><br><strong>Live book:</strong> <a href="https://mrxavier53.github.io/JavaScript_Mastery_by_Mr-Xavier/" target="_blank" rel="noreferrer">Open JavaScript Mastery</a></p><p>Your personal achievement: <strong>${state.read.length}/53 chapters read · ${state.xp} XP</strong>.</p><div class="buttons"><button class="btn-primary" onclick="location.hash='book'">Return to Book</button><button class="btn-secondary" onclick="window.print()">Print Book</button></div></section>`}
function settings(){app.innerHTML=`<section class="section-title"><div class="eyebrow">Settings</div><h2>Make the book yours</h2></section><section class="card"><div class="settings-row"><span>Sound effects</span><button id="soundToggle" class="btn-secondary">${state.sound?"On":"Off"}</button></div><div class="settings-row"><span>Reading progress</span><button id="resetProgress" class="btn-secondary">Reset saved progress</button></div></section>`;$("#soundToggle").onclick=()=>{state.sound=!state.sound;save();settings()};$("#resetProgress").onclick=()=>{if(confirm("Reset saved progress and XP on this device?")){state.read=[];state.xp=0;state.badges=[];save();settings()}}}
function render(){const r=location.hash.replace("#","")||"home"; if(r==="home")home(); else if(r==="book")book(); else if(r==="learn")learn();else if(r==="codelab")codelab();else if(r==="progress")progress();else if(r==="badges")badges();else if(r==="author")author();else if(r==="settings")settings();else if(r==="print"){book()}else home();window.scrollTo(0,0)}
window.addEventListener("hashchange",render);window.addEventListener("load",()=>{updateStats();render();setTimeout(()=>$("#splash").classList.add("hide"),500)});

if ("serviceWorker" in navigator) window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));
