const STORAGE_KEY='jsMasteryXavierState_v1';
function defaultState(){return {completedChapters:[],completedTasks:[],completedProjects:[],quizScores:{},notes:{},theme:'dark'}}
function getState(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return defaultState()}}
function saveState(state){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));applyTheme();renderChrome()}
function currentXP(s=getState()){const q=Object.values(s.quizScores).reduce((a,b)=>a+b*10,0);const chapter=s.completedChapters.length*100;const task=TASKS.filter(t=>s.completedTasks.includes(t.id)).reduce((a,t)=>a+t.xp,0);const proj=PROJECTS.filter(p=>s.completedProjects.includes(p.id)).reduce((a,p)=>a+p.xp,0);return chapter+q+task+proj}
function getLevel(xp){const levels=[['Beginner',0],['Learner',350],['Coder',900],['JavaScript Explorer',1800],['JavaScript Builder',3500],['JavaScript Master',6000]];let chosen=levels[0];levels.forEach(l=>{if(xp>=l[1])chosen=l});return chosen[0]}
function percent(done,total){return total?Math.round((done/total)*100):0}
function esc(str){return String(str).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(message){const e=document.createElement('div');e.className='toast';e.textContent=message;document.body.appendChild(e);setTimeout(()=>e.remove(),2500)}
function applyTheme(){document.body.classList.toggle('light',getState().theme==='light')}
const NAV=[['index.html','🏠','Home'],['learn.html','📘','Learn'],['quiz.html','🧠','Quiz'],['tasks.html','💻','Tasks'],['projects.html','📂','Projects'],['notes.html','📝','Notes'],['badges.html','🏆','Badges'],['progress.html','📊','Progress'],['settings.html','⚙️','Settings']];
function currentFile(){return location.pathname.split('/').pop()||'index.html'}
function navHTML(compact=false){const cur=currentFile();return NAV.map(([href,icon,label])=>`<a href="${href}" class="${cur===href?'active':''}"><span>${icon}</span><span>${compact?label:label}</span></a>`).join('')}
function renderChrome(){const s=getState(),xp=currentXP(s);const sidebar=document.getElementById('sidebar'),top=document.getElementById('topbar'),mobile=document.getElementById('mobileNav');if(sidebar){sidebar.innerHTML=`<a href="index.html" class="brand"><span class="brand-mark">JS</span><span class="brand-text"><strong>JavaScript Mastery</strong><small>by Xavier</small></span></a><nav class="side-nav">${navHTML()}</nav><div class="side-progress"><p>Course progress</p><strong>${s.completedChapters.length}/53 chapters</strong><div class="module-progress"><span style="width:${percent(s.completedChapters.length,53)}%"></span></div></div>`}if(top){top.innerHTML=`<div class="topbar-left"><span class="page-title">JavaScript Mastery by Xavier</span></div><div class="topbar-right"><span class="xp-chip">⚡ ${xp} XP</span><span class="level-chip">${getLevel(xp)}</span></div>`}if(mobile){mobile.innerHTML=NAV.slice(0,5).map(([href,icon,label])=>`<a href="${href}" class="${currentFile()===href?'active':''}"><span>${icon}</span><span>${label}</span></a>`).join('')}}
function completeChapter(id){const s=getState();if(!s.completedChapters.includes(id)){s.completedChapters.push(id);saveState(s);toast('Chapter completed! +100 XP')}else toast('This chapter is already complete.')}
function toggleTask(id){const s=getState();const i=s.completedTasks.indexOf(id);if(i<0){s.completedTasks.push(id);toast('Task completed! XP added.')}else{ s.completedTasks.splice(i,1);toast('Task marked incomplete.')}saveState(s)}
function toggleProject(id){const s=getState();const i=s.completedProjects.indexOf(id);if(i<0){s.completedProjects.push(id);toast('Project completed! Great work.')}else{s.completedProjects.splice(i,1);toast('Project marked incomplete.')}saveState(s)}
function initializeHome(){if(document.body.dataset.page!=='home')return;const s=getState(),next=CHAPTERS.find(c=>!s.completedChapters.includes(c.id))||CHAPTERS[52];document.getElementById('homeStats').innerHTML=[['📘',`${s.completedChapters.length} / 53`,'Chapters complete'],['⚡',currentXP(s),'Total XP'],['🧠',Object.keys(s.quizScores).length,'Quizzes taken'],['🏆',BADGES.filter(b=>b.check(s)).length,'Badges unlocked']].map(x=>`<article class="stat-card"><div class="number">${x[0]} ${x[1]}</div><p>${x[2]}</p></article>`).join('');document.getElementById('continueCard').innerHTML=`<div><span class="eyebrow">NEXT LESSON</span><h3>Chapter ${next.id}: ${esc(next.title)}</h3><p>${esc(next.summary)}</p></div><a class="btn btn-primary" href="learn.html?chapter=${next.id}">Continue →</a>`;document.getElementById('moduleGrid').innerHTML=COURSE_MODULES.map(m=>{const cs=CHAPTERS.filter(c=>c.module===m.id),done=cs.filter(c=>s.completedChapters.includes(c.id)).length;return `<a class="module-card" href="learn.html?chapter=${m.range[0]}"><div class="module-number">${m.icon} MODULE ${m.id}</div><h3>${m.title}</h3><p>${m.description}</p><div class="module-progress"><span style="width:${percent(done,cs.length)}%"></span></div><small class="muted">${done}/${cs.length} chapters complete</small></a>`}).join('')}
document.addEventListener('DOMContentLoaded',()=>{applyTheme();renderChrome();initializeHome()});

// Makes the GitHub Pages site installable in supported browsers.
if ('serviceWorker' in navigator && location.protocol !== 'file:') {
  window.addEventListener('load', () => navigator.serviceWorker.register('service-worker.js').catch(() => {}));
}
